export const conversations: Record<number, string[]> = {
    1: [
        "Welcome, Adventurer! Your idle journey begins here.",
        "You can farm materials, craft equipment, breed slimes, battle monsters.",
        "And earn DITTO as you climb the ranks!",
        "In this world, DITTO is both your reward and your power.",
        "Here's your first mission to get you started.",
        "Let’s start with farming some materials.",
        'Press the menu button on the top left and head to "Farming".',
        "This is where you farm materials that you need to craft weapons and armour.",
        "At the top of the page you will see your current Farming Lvl and XP progress.",
        "The levels for each material show the Farming Lvl required to farm it.",
        "Also note the farming durations and XP earned for each material.",
        'Press "Farm" Barkwood.',
        "At the top of the page, you will be able to see your current activity.",
        "You can only do one activity at a time.",
        "Now, farm some Barkwood to earn some rewards.",
    ],
    2: [
        "Now it's time to learn the art of crafting, and use these gathered materials.",
        'Press the menu button on the top left and head to "Crafting".',
        "This is where you create the weapons and armour you need for combat.",
        "Similar to Farming, these levels show the Crafting Lvl required to craft that equipment.",
        "Expand to see the required items to craft each equipment.",
        'Press "Craft" Rustfang.',
        "Now, finish crafting Rustfang to earn some rewards.",
    ],
    3: [
        "Farming and crafting will continue to progress offline with a max progress duration of 8hrs.",
        "Now, let's gear up for battle.",
        'Press the menu button on the top left and head to "Inventory".',
        "Here you can see your DITTO and GP balances.",
        "GP is our in-game currency and DITTO is our native token/premium currency.",
        '"Inventory" shows everything that your own in-game.',
        "Press on your newly crafted Rustfang and equip it.",
        "Ah, don't forget that you cannot fight monsters without first equipping a Slime.",
        'Press the menu button on the top left and head to "Slime Lab".',
        "This is where you see all the Slimes that you own.",
        "You can also breed slimes here.",
        "Press on one of your owned slimes and equip it.",
        'Head to the "Avatar" page to see your current status.',
        'Here you can see your Slime Avatar, Combat and HP LVLs with XP bar and CP (Combat Power).',
        "Below, you will also see all your equips.",
        "Since we're all geared up, let's dive into combat.",
        'Press the menu button on the top left and head to "Combat".',
        'Domains are your training areas. Some require DITTO/GP to enter.',
        'Expand to see what monsters lie await. These monsters spawn randomly.',
        'Dungeons are your battle trial grounds.',
        'In Dungeons, monsters spawn indefinitely and in order, getting stronger after every floor.',
        'Users compete for leaderboard rankings and DITTO rewards.',
        'Press "Enter" Sparkroot Clearing (Tutorial Domain) and have your first taste of blood.',
    ],
    4: [
        "Combat continues indefinitely until you run away or die.",
        "You can also do combat offline but you will be significantly nerfed.",
        "To get stronger slimes, you can gacha or breed.",
        'Head to the "Gacha" page.',
        "This is where you can randomly draw new slimes with rarities ranging from D - SS.",
    ],
    5: [
        "Now finally, here's a Breeding crash course.",
        "All slimes have traits: Body, Pattern, PrimaryColour, Accent, Detail, EyeColour, EyeShape and Mouth.",
        "For each of these traits, there are 4 genes: Dominant (D) and Hidden (H1, H2, H3).",
        "D genes are expressed to give you combat stats and the cosmetic appearance.",
        "H genes are not expressed but they can be passed down to children.",
        "D genes are passed down at a higher probability than H genes.",
        'Certain pairs of D genes can also lead to a mutation to give the child a completely new D trait.',
        'Open one of your unequipped slimes and "Select for Breeding".',
        'Do that for another unequipped slime.',
        'Press the "Breed" tab.',
        'Here you can see the probabilities that each parent trait will be passed down to the child.',
        'If a trait has probability 100%, it means that all genes of that trait (D, H1, H2, H3) for the child will be the same.',
        'Complete breeding to receive your final tutorial reward.',
    ],
};